name: einfachkeiten_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  # state management
  flutter_bloc: ^8.1.3
  # network status
  connectivity_plus: ^5.0.0
  # functional programming
  dartz: ^0.10.1
  # value equality
  equatable: ^2.0.5
  # flutter sdk
  flutter:
    sdk: flutter
  # service locator
  get_it: ^7.6.0
  # routing
  go_router: ^9.0.3
  # fonts
  google_fonts: ^4.0.4
  # remote api
  http: ^1.1.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.14
  flutter_linkify: ^6.0.0
  audioplayers: ^5.2.1
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Einfachkeiten
      fonts:
       - asset: assets/fonts/einfachkeiten.ttf
